version: '3'

services:

  rsync:
    container_name: rsync
    build: ./
    restart: unless-stopped
    volumes:
      - ../data/source:/data/source:ro
      - ../data/destination:/data/destination
    environment:
      TIMEZONE: "America/Montreal"
      PUID: 1000
      PGID: 1000
      RSYNC_OPTIONS: "--archive --delete --verbose --timeout=3600 --progress"
      CRONTAB_OPTIONS: "0 0 * * *"
